### ISSUE TITLE
setNumVerticalLabels strange scale

### ISSUE THREAD

**Issue by dkovalkov** [jjoe64/GraphView#282]
I'm setting
```
graphView.getGridLabelRenderer().setNumVerticalLabels(6);
```
and getting this graph
https://www.dropbox.com/s/zrdr143c8jn54k0/stat_screen.png?dl=0

I expect top label is 2:30 not 4:10. Is this a bug? Or how I can get it?

**Comment by jjoe64** [comment]
it's because GV tries to generate a viewport with round numbers. But as you are formatting it from number to time, GV does not know what makes sense there.
If you want another viewport there, you have to set it manually.

**Comment by dkovalkov** [comment]
I disabled custom formatter for Y and got the same result:
https://www.dropbox.com/s/v6bgfko1vqvp0ou/stat_screen-2.png?dl=0
What is wrong?

**Comment by jjoe64** [comment]
now it's clear. GV tries to create 6 labels and to get nice numbers it has to make this big viewport.
just play with the number of vertical labels to get a nice result. try 4 or maybe 6.

if your biggest value would be < 125 instead of maybe 145 the labels would be from 0 to 125. because your biggest value is about 145 GV has to use 50-steps and so it results in a big viewport.

**Comment by dkovalkov** [comment]
I understand now. Thank you!
