### ISSUE TITLE
cannot resolve symbol 'addSeries'

### ISSUE THREAD

**Issue by mawills** [jjoe64/GraphView#291]
I copy-pasted the "Create a Line Graph from Java" example from this page on the website
 http://www.android-graphview.org/documentation/how-to-create-a-simple-graph

I imported all of the things android studio asked me to import
import com.jjoe64.graphview.GraphView;
import com.jjoe64.graphview.series.DataPoint;
import com.jjoe64.graphview.series.LineGraphSeries;

but there are 3 errors in the line
graph.addSeries(series);

it says
Cannot resolve symbol 'addSeries'
Unknown class:'series'
Unnecessary semicolon

![errorandstu](https://cloud.githubusercontent.com/assets/10565899/6138292/ccb46a16-b14d-11e4-980d-aa3a332ed36d.png)

**Comment by pdaddy26** [comment]
How did you include the graphview ? 

Did you try with gradle? It is way simpler with gradle, just add this to the gradle build file

dependencies {
    compile 'com.jjoe64:graphview:4.0.0'
}

**Comment by finneysm7** [comment]
I ran into the same problem while trying to add GraphView and follow the tutorial. Unfortunately for me, I could not simply have GraphView enabled by moving the .jar file into my libs folder. Putting it into the gradle dependencies resulted in addSeries to be unrecognized.

I am considering using a different library because I simply cannot get the method addSeries to be recognized on my GraphView class. Perhaps I can find a way to have the .jar file recognized by the app when I move it to the libs file.
