### ISSUE TITLE
bar graph out of viewport on scroll

### ISSUE THREAD

**Issue by silvioAL** [jjoe64/GraphView#569]
Hi there,

the bar of the graph is beeins plotted outside of the grid,  sometimes overlapping the labels when scrolling.
![captura de tela 2018-04-19 as 16 51 42](https://user-images.githubusercontent.com/24980257/39015089-a39adf12-43f2-11e8-81a1-01938cac68af.png)

![captura de tela 2018-04-19 as 16 52 35](https://user-images.githubusercontent.com/24980257/39014990-550ffd46-43f2-11e8-8489-2848f75af9c2.png)

**Comment by appsthatmatter** [comment]
please check your data that you use. if it's really a bug then provide a isolated example where i can debug it

**Comment by silvioAL** [comment]
Ok, I've created an project for that, than you cant download and reproduce:

https://github.com/silvioAL/GraphicsIssue

**Comment by oscarsan1** [comment]
I've found same issue. Try it with your demos. If you change the advanced bar graph including: 
        graph.getViewport().setScalable(true);
you can reproduce this issue, when moving or scaling the graph, the bar goes into the labels.

**Comment by oscarsan1** [comment]
There is a bug with bar graph and scalable set.
A work arround is to add the marked line in the graphbarseries.java:

            // overdraw
            left = Math.max(left, contentLeft);
            right = Math.min(right, contentLeft+contentWidth);
-->>            right = Math.max(right,left);
            bottom = Math.min(bottom, contentTop+contentHeight);
            top = Math.max(top, contentTop);

            mDataPoints.put(new RectD(left, top, right, bottom), value);

            Paint p;
            if (mCustomPaint != null) {
                p = mCustomPaint;
            } else {
                p = mPaint;
            }
            canvas.drawRect((float)left, (float)top, (float)right, (float)bottom, p);

The problem is when left is bigger than right, the function drawRect draw also the rectangle.

There is algo another bug with the width of the bar thar didn't chage until the zoom is enough for substract a bar from display. I'm try to solve it but is much dificult. In the end the bar graph is not very suited for scaling.

**Comment by serazsani** [comment]
Hi,

This was supposed to be fixed on Apr 5, 2019 right? I am getting the same issue currently, using version 4.2.2
![image](https://user-images.githubusercontent.com/64314016/141644458-222ed1c8-bf79-4d3b-a52d-fd20349fdace.png)
